### ISSUE TITLE
Force-collapse Threads?

### ISSUE THREAD

**Issue by macintacos** [leggett/simplify#261]
Not entirely sure why this isn't working, but it seems to happen for emails that I get after I subscribe to an issue in Jira (I know, niche-ish usecase); all of the emails don't get "condensed" down to where it shows just a number and an excerpt of the first/last email, it continues to show a row for all messages in the thread, which makes it so that I _always_ have to scroll down to see the latest message.

For example, it doesn't look like this:

https://p-37FYgJ.b1.n0.cdn.getcloudapp.com/items/WnuN57qo/Image%202020-03-26%20at%2014.09.18.png?v=a9924438a0ce7d141b98f3c0b327b239

It looks like this:

https://p-37FYgJ.b1.n0.cdn.getcloudapp.com/items/wbumOXbz/Image%202020-03-26%20at%2014.07.31.png?v=da02bd533ae14f07a7d36588b3a28d38

Is this something that could be "enforced" by this extension?

**Comment by macintacos** [comment]
In the meantime, I reverse threads using this CSS I found somewhere online, which solves it most of the time:

```css
div[role=list]:not(.brd) {
    display: flex;
    flex-direction: column-reverse;
}

div[role=listitem] {
    flex: 0 0 auto;
}

div[role=listitem].h7>div>div>div>div {
    display: flex;
    flex-direction: column-reverse;
}

div[role=listitem].h7>div>div>div>div>div {
    flex: 0 0 auto;
}
.kQ {
    margin: 1px;
}

/*reverse printing veiw*/
body:not([class]) > div.bodycontainer > div.maincontent {
    display: flex;
    flex-direction: column-reverse;
}
body:not([class]) > div.bodycontainer > div.maincontent > table:nth-child(1) {
  order: 1;
  padding-bottom: 5px;
  margin-bottom: 10px;
  border-bottom-width: 1px;
  border-color: gray;
  border-style: solid;
}

/* response field height */
div.amn {
    height:25px !important;
}
div[role=listitem] .gB.xu {
	border-bottom: 0px !important;
}

/* frames */
div[role=listitem].kv>div>div,
div[role=listitem].kQ>div>div,
div[role=listitem].h7>div>div {
	border-top: 0 !important;
	border-bottom: 1px solid #d8d8d8 !important;
}

div[role=listitem].h7:last-child .adn {
	border-top: 1px solid #d8d8d8 !important;
	border-bottom: 0 solid #d8d8d8 !important;
	padding-top: 5px !important;
	margin-top: 10px !important;
}
/* response and forward buttons */
.h7.ie .gA>.gB>.ip {
    padding: 5px 0 !important;
}
.h7.ie .gA>.gB>.ip .brb {
    margin-bottom: 14px !important;
    padding-bottom: 3px !important;
}

/* fixed addresses bar */
.Bk td.I5>form.bAs>div:nth-child(1) {
  height: 0px !important;
}
.Bk td.I5>form.bAs>div:nth-child(2) {
  position: static !important;
}
.Bk div.ajn.azy {
  position: static !important;
}
```

But it'd be nice to actually keep the "default" ordering and just make the already-read messages more compact.
