### ISSUE TITLE
Compatibility with Mailvelope Chrome Plugin

### ISSUE THREAD

**Issue by macx** [leggett/simplify#774]
I'm using the [Mailvelope](https://mailvelope.com/en) Chrome Plugin.
It injects a second compose button which is not matching with the compose button, Simplify is styling. Please support Mailvelope!

But I wrote some CSS using Stylus to get this result:

![Screenshot 20231207-1 1135 Google Chrome@2x](https://github.com/leggett/simplify/assets/84112/ac34cbfe-5edb-447a-b468-47c7eab48226)

```css
@-moz-document domain("mail.google.com") {
	/* SimpliFy Gmail comp. with Mailvelope */
    html.simplify.composeFab body[data-mailvelope-version] .aeN .z0,
	html.simplify.newNav.composeFab body[data-mailvelope-version] .aqn.aIH .z0 {
		flex-direction: column;
		justify-content: flex-end;
    	height: 7rem;
    	gap: 12px;		
	}
	
	html.simplify.composeFab body[data-mailvelope-version] .aeN .z0 > div:nth-child(2),
	html.simplify.newNav.composeFab body[data-mailvelope-version] .aqn.aIH .z0 > div:nth-child(2) {
		margin: 0 !important;
	}
	
	html.simplify.composeFab body[data-mailvelope-version] #composeMenu {
		bottom: 150px;
	}
}
```
